//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.TaskLocations = new HashSet<TaskLocation>();
        }
    
        public int location_id { get; set; }
        public string title { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }

        [JsonIgnore]
        public virtual ICollection<TaskLocation> TaskLocations { get; set; }
    }
}
