//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Radius
    {
        public Radius()
        {
            this.TaskLocations = new HashSet<TaskLocation>();
        }
    
        public int radius_id { get; set; }
        public string description { get; set; }
        public int radius_distance { get; set; }
        public string unit { get; set; }

        [JsonIgnore]
        public virtual ICollection<TaskLocation> TaskLocations { get; set; }
    }
}
