//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class TaskLocation
    {
        public int task_location_id { get; set; }
        public int task_id { get; set; }
        public int location_id { get; set; }
        public int radius_id { get; set; }
        public System.Guid alternate_id { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Radius Radius { get; set; }
        [JsonIgnore]
        public virtual Task Task { get; set; }
    }
}
